### ISSUE TITLE
typo line 88,89 sandbox.py

### ISSUE THREAD

**Issue by alre5639** [KasperGroesLudvigsen/influenza_transformer#11]
I believe there is a typo in sandbox.py line 88 and 89.

`
src, trg, trg_y = batch

# Permute from shape [batch size, seq len, num features] to [seq len, batch size, num features]
if batch_first == False:

    shape_before = src.shape
    src = src.permute(1, 0, 2)
    print("src shape changed from {} to {}".format(shape_before, src.shape))

    shape_before = tgt.shape
    tgt = tgt.permute(1, 0, 2)
    print("src shape changed from {} to {}".format(shape_before, src.shape))
`

tgt does not exist in this context atm. I believe tgt s/b trg.

**Comment by Eran-BA** [comment]
you right, I think
