### ISSUE TITLE
multivariate predict variate

### ISSUE THREAD

**Issue by LiuYang200** [KasperGroesLudvigsen/influenza_transformer#2]
Hello.  My data has multiple input features. How should I modify transfomer?

**Comment by MasterKinjalk** [comment]
> has multiple input features. How should I modify transfomer?

Did you figure it out?

**Comment by LiuYang200** [comment]
> > has multiple input features. How should I modify transfomer?
> 
> Did you figure it out?

no

**Comment by KasperGroesLudvigsen** [comment]
Hi there! The current implementation should be able to handle multiple input features in the encoder. I have not yet used it with multiple input features in the decoder.

**Comment by LiuYang200** [comment]
> Hi there! The current implementation should be able to handle multiple input features in the encoder. I have not yet used it with multiple input features in the decoder.

Thanks a million

**Comment by anshumansinha16** [comment]
Hi, did you figure out ? I need to predict multivariate outputs as well. What changes were needed at the decoder end?

> > Hi there! The current implementation should be able to handle multiple input features in the encoder. I have not yet used it with multiple input features in the decoder.
> 
> Thanks a million
