### ISSUE TITLE
There are negative values in the output, how to get the predicted value? Thank you

### ISSUE THREAD

**Issue by Linda-L** [KasperGroesLudvigsen/influenza_transformer#6]
output:tensor([[ 0.9394, -0.0657, -0.5242,  ..., -0.3573, -0.3968, -0.8111],
        [ 0.3269,  0.1186, -0.4571,  ..., -0.1672,  0.0763, -0.6789],
        [ 0.8612,  0.2685, -0.3978,  ..., -0.2583,  0.0484, -0.9527],
        ...,
        [ 0.8189, -0.3896, -0.2842,  ..., -0.5775, -0.3065, -0.8513],
        [ 0.5229,  0.0786, -0.3587,  ..., -0.1097, -0.3169, -0.6342],
        [ 0.8320, -0.1121, -0.6839,  ..., -0.6073,  0.0972, -0.7809]],
       grad_fn=<AddmmBackward0>)
output_size:torch.Size([128, 48])

**Comment by KasperGroesLudvigsen** [comment]
You need to train the network to give meaningful outputs :)
